#!/usr/bin/env python3
import sys
import re

OPCODES = {
    'LDI': 0x01,
    'LDR': 0x02,
    'STR': 0x03,
    'ADD': 0x04,
    'SUB': 0x05,
    'JMP': 0x06,
    'JZ':  0x07,
    'AND': 0x08,
    'OR':  0x09,
    'XOR': 0x0A,
    'SHL': 0x0B,
    'SHR': 0x0C,
    'CALL': 0x0D,
    'RET': 0x0E,
    'JNZ': 0x0F,
    'JC':  0x10,
    'NOP': 0xFF
}

def assemble(filepath):
    with open(filepath, 'r') as f:
        lines = f.readlines()
        
    labels = {}
    clean_lines = []
    
    # First pass: resolve labels
    addr = 0
    for line in lines:
        line = line.split(';')[0].strip()
        if not line:
            continue
            
        if line.endswith(':'):
            labels[line[:-1]] = addr
        else:
            clean_lines.append(line)
            addr += 2 # Every instruction is 2 bytes

    # Second pass: generate code
    machine_code = []
    current_addr = 0
    for line in clean_lines:
        parts = line.split()
        opcode = parts[0].upper()
        
        if opcode not in OPCODES:
            print(f'Error: Unknown opcode {opcode}')
            sys.exit(1)
            
        byte1 = OPCODES[opcode]
        byte2 = 0x00
        
        if len(parts) > 1:
            operand = parts[1]
            if operand in labels:
                byte2 = labels[operand]
            elif operand.startswith('0x'):
                byte2 = int(operand, 16)
            elif operand.isdigit():
                byte2 = int(operand)
            else:
                print(f'Error: Invalid operand {operand}')
                sys.exit(1)
                
        machine_code.append((byte1, byte2, line, current_addr))
        current_addr += 2
        
    return machine_code

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print('Usage: python assembler.py <source.asm>')
        sys.exit(1)
        
    binary = assemble(sys.argv[1])
    
    print('/* Auto-generated by TinySoC Assembler */')
    print(f'const uint8_t firmware[{len(binary)*2}] = {{')
    for b1, b2, text, addr in binary:
        print(f'    0x{b1:02X}, 0x{b2:02X}, // 0x{addr:02X}: {text}')
    print('};')
 
