name: test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y iverilog verilator

      # Set Python up and install cocotb
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        shell: bash
        run: pip install -r test/requirements.txt

      - name: Run tests
        shell: bash
        run: |
          cd test
          find . -name "verification_run.log" -delete
          make all || {
            echo ""
            echo "========== isa/verification_run.log =========="
            tail -n 50 */*_run.log
            echo "==============================================="
            exit 1
          }

      - name: upload vcd
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-vcd
          path: |
            test/**/*.vcd
            test/**/*.log
 
